### ISSUE TITLE
Are the side chain packing only around the pocket?

### ISSUE THREAD

**Issue by KSUN63** [Zhang-Runze/PackDock#3]
Hi Runze,

The result of your model is really impressive for the protein side-chain packing task! I was browsing your repo and do you think your method should be capable of doing the side chain repacking for the entire protein? Maybe by defining the binding pocket to be the entire protein? Have you ever done any benchmarking in that regard?

Thanks,
Oliver

**Comment by Zhang-Runze** [comment]
Hi Oliver,

Thanks a lot for your interest in PackDock!
This project mainly focuses on protein pocket areas, which are crucial in structure-based drug design. As a result, we didn't evaluate PackPocket's repacking performance for the entire protein. However, we believe that this framework can be directly used in the entire protein repacking training process.
If you have any other questions or need further information, please feel free to contact me. You can also email me.

Best,
Runze

**Comment by KSUN63** [comment]
Thanks! I'll give it a try and ask you if I have other questions
