### ISSUE TITLE
Reference ligand position for get pockets

### ISSUE THREAD

**Issue by ld139** [Zhang-Runze/PackDock#4]
Hi,

Thank you for your excellent work. I am curious about how to extract the ligand pocket for packing or docking when testing the apo2holo datasets, especially since the apo.pdb files in these datasets do not contain any ligands. Could you possibly provide the processed apo2holo datasets?

Best wishes

**Comment by Zhang-Runze** [comment]
Thank you very much for your interest in PackDock! I sincerely apologize for the delayed response.

To evaluate the ability of flexible molecular docking in a given pocket, we align the holo and apo structures when using the apo2holo datasets. We then use the ligand from the holo to define the pocket region of the apo structures. In fact, the authors of the apo2holo dataset have already performed the alignment process.

If you have any further questions, please do not hesitate to contact me. Or you can also email me.
