### ISSUE TITLE
Why does the output conformation pdb files contain multiple models?

### ISSUE THREAD

**Issue by Amplifier-seller** [Zhang-Runze/PackDock#5]
Excellent work! There's only one small question about my try. When I successfully ran PackPocket on my protein (without ligand) with the following command:
```bash
python -m evaluate_protein --run_name test --inference_steps 20 --samples_per_complex 10 --batch_size 2 --actual_steps 20 --cache_path data/ --no_final_step_noise --data_dir ./AF_worse_preprocessed/ --split_path data/splits/AF_worse_split --save_visualisation --num_workers 1
```
I found that the 10 output `.pdb` files all possess 23 models, and most of them have different atom coordinates. I wonder their meanings in the output, do they represent the generative procedures or anything else? And which one of them should I use for following work?

**Comment by Zhang-Runze** [comment]
Thank you for your interest in PackPocket!

Each output PDB file contains the complete side-chain generation process, indicating that each model represents the protein conformation at a different time step t in the diffusion model. You can use the final model for further processing.

If you have any other questions, please don't hesitate to contact me. You can also contact me via email.
